# Generated by Django 5.0.7 on 2024-08-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('MobileNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('plan', models.CharField(choices=[('5 year', '2 year'), ('10 year', '1 year'), ('1 month', '2 month')], max_length=30)),
            ],
        ),
    ]
